from PIL import Image
import sys
import os

def remove_background(input_path, output_path, tolerance=30):
    try:
        img = Image.open(input_path).convert("RGBA")
        datas = img.getdata()
        
        # Simple thresholding might kill highlights.
        # Let's use floodfill from corners.
        # Create a mask image
        from PIL import ImageDraw
        
        # Seed points: 4 corners
        width, height = img.size
        seeds = [(0, 0), (width-1, 0), (0, height-1), (width-1, height-1)]
        
        # We'll use Image.floodfill-like approach manually or using a library logic
        # Since PIL doesn't have a direct 'floodfill to transparent' for partial matches easily without logic.
        # Let's try a simpler approach first: "Magic Wand" on white.
        # Since the background is PURE WHITE generated by DALL-E/Gemini usually.
        
        newData = []
        for item in datas:
            # Check if pixel is white (or very close to it)
            if item[0] > 255 - tolerance and item[1] > 255 - tolerance and item[2] > 255 - tolerance:
                newData.append((255, 255, 255, 0)) # Transparent
            else:
                newData.append(item)
        
        img.putdata(newData)
        
        # Optional: Trim to content? No, keep size consistent.
        
        img.save(output_path, "PNG")
        print(f"Processed {input_path} -> {output_path}")
        
    except Exception as e:
        print(f"Error processing {input_path}: {e}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python remove_bg.py <input_file> [output_file]")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else input_file
    
    remove_background(input_file, output_file)
